// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBoS7lFut9g7tj0XdAKwQ2Tx88XIR4kU',
    appId: '1:234186880912:web:c1c3de385bf9f6b5082515',
    messagingSenderId: '234186880912',
    projectId: 'alor-poth-72ea0',
    authDomain: 'alor-poth-72ea0.firebaseapp.com',
    storageBucket: 'alor-poth-72ea0.firebasestorage.app',
    measurementId: 'G-ZNVFS9TFLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwDMu_SabcmboyloOjcnLjD0YKVbPaVE',
    appId: '1:234186880912:android:2f7081fcf5d6b0a1082515',
    messagingSenderId: '234186880912',
    projectId: 'alor-poth-72ea0',
    storageBucket: 'alor-poth-72ea0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDvE6hg1zq92HyW0mVE1IgZrCCiFzTaRs',
    appId: '1:234186880912:ios:c43d956d90a7d9ca082515',
    messagingSenderId: '234186880912',
    projectId: 'alor-poth-72ea0',
    storageBucket: 'alor-poth-72ea0.firebasestorage.app',
    iosClientId: '234186880912-9is6fn8422ts287l9kqh5huui9k5kq9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.alorPoth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDvE6hg1zq92HyW0mVE1IgZrCCiFzTaRs',
    appId: '1:234186880912:ios:c43d956d90a7d9ca082515',
    messagingSenderId: '234186880912',
    projectId: 'alor-poth-72ea0',
    storageBucket: 'alor-poth-72ea0.firebasestorage.app',
    iosClientId: '234186880912-9is6fn8422ts287l9kqh5huui9k5kq9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.alorPoth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQBoS7lFut9g7tj0XdAKwQ2Tx88XIR4kU',
    appId: '1:234186880912:web:3d2dea4352df52cb082515',
    messagingSenderId: '234186880912',
    projectId: 'alor-poth-72ea0',
    authDomain: 'alor-poth-72ea0.firebaseapp.com',
    storageBucket: 'alor-poth-72ea0.firebasestorage.app',
    measurementId: 'G-2LT1QTNT9L',
  );
}
